road_safety:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      port: 5432
      user: dwh
      password: "{{ env_var('DB_PASSWORD') }}"
      dbname: road_safety
      schema: dbt
      threads: 2